// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbiofjzkrwyxellycior.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiaW9manprcnd5eGVsbHljaW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNDQ1MjQsImV4cCI6MjA0OTcyMDUyNH0.Ay2GdH1Xa94DAAYMXHz5Iy4A8k_2GQ1rfo3AJu2V_8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);