// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnvaqtbcdssgdlyjhdyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudmFxdGJjZHNzZ2RseWpoZHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxOTIyMTcsImV4cCI6MjA0OTc2ODIxN30.Wpse3elnzRp9tACkMlm9umJECxeXFokLqIM6RglrTcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);